<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ActividadEconomica;

class ActividadIndustrialSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $actividades = [
            'Cultivo de cereales(excepto arroz), leguminosas y semillas oleaginosas',
            'Cultivo de arroz',
            'Cultivo de hortalizas y melones, raíces y tubérculos',
            'Cultivo de caña de azúcar',
            'Cultivo de tabaco',
            'Cultivo de plantas para fibras textiles',
            'Cultivo de otros productos agrícolas no perennes',
            'Cultivo de uva',
            'Cultivo de frutas tropicales y subtropicales',
            'Cultivo de cítricos',
            'Cultivo de frutas de pepita y de hueso',
            'Cultivo de otros frutos y nueces de árboles y arbustos',
            'Cultivo de frutos oleaginosos',
            'Cultivo de plantas con las que se preparan bebidas',
            'Cultivo de especias y de plantas aromáticas, medicinales y farmacéuticas',
            'Cultivo de otras plantas perennes',
            'Propagación de plantas',
            'Cría de ganado bovino y búfalos',
            'Cría de caballos y otros équidos',
            'Cría de camellos y otros camélidos',
            'Cría de ovejas y cabras',
            'Cría de cerdos',
            'Cría de aves de corral',
            'Cría de otros animales',
            'Cultivo de productos agrícolas en combinación con la cría de animales (explotación mixta)',
            'Tratamiento de semillas para propagación',
            'Extracción de madera',
            'Acuicultura marina',
            'Acuicultura de agua dulce',
            'Elaboración y conservación de carne',
            'Elaboración y conservación de pescado, crustáceos y moluscos',
            'Elaboración y conservación de frutas, legumbres y hortalizas',
            'Elaboración de aceites y grasas de origen vegetal y animal',
            'Elaboración de productos lácteos',
            'Elaboración de productos de molienda',
            'Elaboración de almidones y productos derivados del almidón',
            'Elaboración de productos de panadería',
            'Elaboración de azúcar',
            'Elaboración de cacao y chocolate y de productos de confitería',
            'Elaboración de macarrones, fideos, alcuzcuz y productos farináceos similares',
            'Elaboración de comidas y platos preparados',
            'Elaboración de otros productos alimenticios no considerados principales',
            'Elaboración de alimentos preparados para animales',
            'Destilación, rectificación y mezcla de bebidas alcohólicas',
            'Elaboración de vinos',
            'Elaboración de malta y licores de malta',
            'Elaboración de bebidas no alcohólicas, producción de aguas minerales y otras aguas embotelladas',
            'Elaboración de productos de tabaco',
            'Preparación e hilatura de fibras textiles',
            'Tejedura de productos textiles',
            'Acabado de productos textiles',
            'Fabricación de tejidos de punto y ganchillo',
            'Fabricación de artículos confeccionados de materiales textiles, excepto prendas de vestir',
            'Fabricación de tapices y alfombras',
            'Fabricación de cuerdas, cordeles, bramantes y redes',
            'Fabricación de otros productos textiles no considerados principales',
            'Fabricación de prendas de vestir, excepto prendas de piel',
            'Fabricación de artículos de piel',
            'Fabricación de artículos de punto y ganchillo',
            'Curtido y adobo de cueros, adobo y teñido de pieles',
            'Fabricación de maletas, bolsos de mano y artículos similares, y de artículos de talabartería y guarnicionería',
            'Fabricación de calzado',
            'Aserrado y acepilladura de madera',
            'Fabricación de hojas de madera para enchapado y tableros a base de madera',
            'Fabricación de partes y piezas de carpintería para edificios y construcciones',
            'Fabricación de recipientes de madera',
            'Fabricación de otros productos de madera, fabricación de artículos de corcho, paja y materiales trenzables',
            'Fabricación de pasta de madera, papel y cartón',
            'Fabricación de papel y cartón ondulado y de envases de papel y cartón',
            'Fabricación de otros artículos de papel y cartón',
            'Impresión',
            'Actividades de servicios relacionadas con la impresión',
            'Reproducción de grabaciones',
            'Fabricación de productos de hornos de coque',
            'Fabricación de productos de la refinación del petróleo',
            'Fabricación de sustancias químicas básicas',
            'Fabricación de abonos y compuestos de nitrógeno',
            'Fabricación de plásticos y caucho sintético en formas primarias',
            'Fabricación de plaguicidas y otros productos químicos de uso agropecuario',
            'Fabricación de pinturas, barnices y productos de revestimiento similares, tintas de imprenta y masillas',
            'Fabricación de jabones y detergentes, preparados para limpiar y pulir, perfumes y preparados de tocador',
            'Fabricación de otros productos químicos no considerados principales',
            'Fabricación de fibras artificiales',
            'Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos de uso farmacéutico',
            'Fabricación de llantas y tubos de hule, reconstrucción y revitalizado de llantas de hule',
            'Fabricación de otros productos de caucho',
            'Fabricación de productos de plástico',
            'Fabricación de productos refractarios',
            'Fabricación de materiales de construcción de arcilla',
            'Fabricación de otros productos de porcelana y de cerámica',
            'Fabricación de cemento, cal y yeso',
            'Fabricación de artículos de hormigón, cemento y yeso',
            'Corte, talla y acabado de la piedra',
            'Fabricación de otros productos minerales no metálicos no considerados principales',
            'Industrias básicas de hierro y acero',
            'Fabricación de metales preciosos básicos y de otros metales no ferrosos',
            'Fundición de hierro y acero',
            'Fundición de metales no ferrosos',
            'Fabricación de productos metálicos para uso estructural',
            'Fabricación de tanques, depósitos y recipientes de metal',
            'Fabricación de generadores de vapor, excepto calderas de agua caliente para calefacción central',
            'Fabricación de armas y municiones',
            'Forja, prensado, estampado y laminado de metales, pulvimetalurgia',
            'Tratamiento y revestimiento de metales, maquinado',
            'Fabricación de artículos de cuchillería, herramientas de mano y artículos de ferretería',
            'Fabricación de otros productos elaborados de metal no considerados principales',
            'Fabricación de componentes y tableros electrónicos',
            'Fabricación de ordenadores (computadoras) y equipo periférico',
            'Fabricación de equipo de comunicaciones',
            'Fabricación de aparatos electrónicos de consumo',
            'Fabricación de equipo de medición, prueba, navegación y control',
            'Fabricación de relojes',
            'Fabricación de equipo de irradiación y equipo electrónico de uso médico y terapéutico',
            'Fabricación de instrumentos ópticos y equipo fotográfico',
            'Fabricación de soportes magnéticos y ópticos',
            'Fabricación de motores, generadores y transformadores eléctricos y aparatos de distribución y control de la energía eléctrica',
            'Fabricación de pilas, baterías y acumuladores',
            'Fabricación de cables de fibra óptica',
            'Fabricación de otros hilos y cables eléctricos',
            'Fabricación de dispositivos de cableado',
            'Fabricación de equipo eléctrico de iluminación',
            'Fabricación de aparatos de uso doméstico',
            'Fabricación de otros tipos de equipo eléctrico',
            'Fabricación de motores y turbinas, excepto motores para aeronaves, vehículos automotores y motocicletas',
            'Fabricación de equipo de propulsión de fluidos',
            'Fabricación de otras bombas, compresores, grifos y válvulas',
            'Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión',
            'Fabricación de hornos, hogares y quemadores',
            'Fabricación de equipo de elevación y manipulación',
            'Fabricación de maquinaria y equipo de oficina [excepto ordenadores (computadoras) y equipo periférico]',
            'Fabricación de herramientas de mano motorizadas',
            'Fabricación de otros tipos de maquinaria de uso general',
            'Fabricación de maquinaria agropecuaria y forestal',
            'Fabricación de maquinaria para la conformación de metales y de máquinas herramienta',
            'Fabricación de maquinaria metalúrgica',
            'Fabricación de maquinaria para la explotación de minas y canteras y para obras de construcción',
            'Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco',
            'Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestir y cueros',
            'Fabricación de otros tipos de maquinaria de uso especial',
            'Fabricación de vehículos automotores',
            'Fabricación de carrocerías para vehículos automotores, fabricación de remolques y semirremolques',
            'Fabricación de partes, piezas y accesorios para vehículos automotores',
            'Construcción de buques y estructuras flotantes',
            'Construcción de embarcaciones de recreo y de deporte',
            'Fabricación de locomotoras y material rodante',
            'Fabricación de aeronaves, naves espaciales y maquinaria conexa',
            'Fabricación de motocicletas',
            'Fabricación de bicicletas y de sillones de ruedas para inválidosdiscapacidad física',
            'Fabricación de otros tipos de equipo de transporte no considerada principal',
            'Fabricación de muebles',
            'Fabricación de joyas y artículos conexos',
            'Fabricación de bisutería y artículos conexos',
            'Fabricación de instrumentos de música',
            'Fabricación de artículos de deporte',
            'Fabricación de juegos y juguetes',
            'Fabricación de instrumentos y materiales médicos y odontológicos',
            'Otras industrias manufactureras no consideradas principales',
            'Reparación de productos elaborados de metal',
            'Reparación de maquinaria',
            'Reparación de equipo electrónico y óptico',
            'Reparación de equipo eléctrico',
            'Reparación de equipo de transporte, excepto vehículos automotores',
            'Reparación de otros tipos de equipo',
            'Instalación de maquinaria y equipo industriales',
            'Tratamiento y eliminación de desechos no peligrosos',
            'Tratamiento y eliminación de desechos peligrosos',
            'Recuperación de materiales',
            'Reparación de ordenadores (computadoras) y equipo periférico',
            'Reparación de equipo de comunicaciones',
            'Reparación de aparatos electrónicos de consumo',
            'Reparación de aparatos de uso doméstico y equipo doméstico y de jardinería',
            'Reparación de calzado y de artículos de cuero',
            'Reparación de muebles y accesorios domésticos',
            'Reparación de otros efectos personales y enseres domésticos',
        ];

        foreach ($actividades as $descripcion) {
            ActividadEconomica::create([
                'descripcion' => $descripcion,
                'funcion_id'  => 5,
            ]);
        }
    }
}
